dist: xenial
# Use the latest Travis images since they are more up to date than the stable release.
group: edge
jobs:
    include:
    
    # Run Frontend JS tests
    - language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.16.1'
      cache: npm
      before_install:
        - cd frontend/
      install:
        - npm install --frozen-lockfile
      script:
        - npm test
        - npm build

    # Run Backend JS tests
    - language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.16.1'
      cache: yarn
      before_install:
        - cd backend/
      install:
        - npm install --frozen-lockfile
      script:
        - npm test
